package com.atguigu.PbAndJson;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

public final class Mobile {
  private Mobile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HardwareOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Hardware)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 rom = 1;</code>
     * @return Whether the rom field is set.
     */
    boolean hasRom();
    /**
     * <code>required int32 rom = 1;</code>
     * @return The rom.
     */
    int getRom();

    /**
     * <code>required int32 ram = 2;</code>
     * @return Whether the ram field is set.
     */
    boolean hasRam();
    /**
     * <code>required int32 ram = 2;</code>
     * @return The ram.
     */
    int getRam();

    /**
     * <code>required int32 size = 3;</code>
     * @return Whether the size field is set.
     */
    boolean hasSize();
    /**
     * <code>required int32 size = 3;</code>
     * @return The size.
     */
    int getSize();
  }
  /**
   * Protobuf type {@code Hardware}
   */
  public static final class Hardware extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Hardware)
      HardwareOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hardware.newBuilder() to construct.
    private Hardware(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hardware() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Hardware();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Hardware(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              rom_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ram_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              size_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Mobile.internal_static_Hardware_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Mobile.internal_static_Hardware_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Mobile.Hardware.class, Mobile.Hardware.Builder.class);
    }

    private int bitField0_;
    public static final int ROM_FIELD_NUMBER = 1;
    private int rom_;
    /**
     * <code>required int32 rom = 1;</code>
     * @return Whether the rom field is set.
     */
    @java.lang.Override
    public boolean hasRom() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 rom = 1;</code>
     * @return The rom.
     */
    @java.lang.Override
    public int getRom() {
      return rom_;
    }

    public static final int RAM_FIELD_NUMBER = 2;
    private int ram_;
    /**
     * <code>required int32 ram = 2;</code>
     * @return Whether the ram field is set.
     */
    @java.lang.Override
    public boolean hasRam() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 ram = 2;</code>
     * @return The ram.
     */
    @java.lang.Override
    public int getRam() {
      return ram_;
    }

    public static final int SIZE_FIELD_NUMBER = 3;
    private int size_;
    /**
     * <code>required int32 size = 3;</code>
     * @return Whether the size field is set.
     */
    @java.lang.Override
    public boolean hasSize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 size = 3;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRam()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, rom_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, ram_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, size_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rom_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ram_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, size_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Mobile.Hardware)) {
        return super.equals(obj);
      }
      Mobile.Hardware other = (Mobile.Hardware) obj;

      if (hasRom() != other.hasRom()) return false;
      if (hasRom()) {
        if (getRom()
            != other.getRom()) return false;
      }
      if (hasRam() != other.hasRam()) return false;
      if (hasRam()) {
        if (getRam()
            != other.getRam()) return false;
      }
      if (hasSize() != other.hasSize()) return false;
      if (hasSize()) {
        if (getSize()
            != other.getSize()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRom()) {
        hash = (37 * hash) + ROM_FIELD_NUMBER;
        hash = (53 * hash) + getRom();
      }
      if (hasRam()) {
        hash = (37 * hash) + RAM_FIELD_NUMBER;
        hash = (53 * hash) + getRam();
      }
      if (hasSize()) {
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getSize();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Mobile.Hardware parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Mobile.Hardware parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Mobile.Hardware parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Mobile.Hardware parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Mobile.Hardware parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Mobile.Hardware parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Mobile.Hardware parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Mobile.Hardware parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Mobile.Hardware parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Mobile.Hardware parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Mobile.Hardware parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Mobile.Hardware parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Mobile.Hardware prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Hardware}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Hardware)
        Mobile.HardwareOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Mobile.internal_static_Hardware_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Mobile.internal_static_Hardware_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Mobile.Hardware.class, Mobile.Hardware.Builder.class);
      }

      // Construct using Mobile.Hardware.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rom_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ram_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Mobile.internal_static_Hardware_descriptor;
      }

      @java.lang.Override
      public Mobile.Hardware getDefaultInstanceForType() {
        return Mobile.Hardware.getDefaultInstance();
      }

      @java.lang.Override
      public Mobile.Hardware build() {
        Mobile.Hardware result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Mobile.Hardware buildPartial() {
        Mobile.Hardware result = new Mobile.Hardware(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rom_ = rom_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ram_ = ram_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.size_ = size_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Mobile.Hardware) {
          return mergeFrom((Mobile.Hardware)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Mobile.Hardware other) {
        if (other == Mobile.Hardware.getDefaultInstance()) return this;
        if (other.hasRom()) {
          setRom(other.getRom());
        }
        if (other.hasRam()) {
          setRam(other.getRam());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRom()) {
          return false;
        }
        if (!hasRam()) {
          return false;
        }
        if (!hasSize()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Mobile.Hardware parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Mobile.Hardware) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rom_ ;
      /**
       * <code>required int32 rom = 1;</code>
       * @return Whether the rom field is set.
       */
      @java.lang.Override
      public boolean hasRom() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 rom = 1;</code>
       * @return The rom.
       */
      @java.lang.Override
      public int getRom() {
        return rom_;
      }
      /**
       * <code>required int32 rom = 1;</code>
       * @param value The rom to set.
       * @return This builder for chaining.
       */
      public Builder setRom(int value) {
        bitField0_ |= 0x00000001;
        rom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rom = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rom_ = 0;
        onChanged();
        return this;
      }

      private int ram_ ;
      /**
       * <code>required int32 ram = 2;</code>
       * @return Whether the ram field is set.
       */
      @java.lang.Override
      public boolean hasRam() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 ram = 2;</code>
       * @return The ram.
       */
      @java.lang.Override
      public int getRam() {
        return ram_;
      }
      /**
       * <code>required int32 ram = 2;</code>
       * @param value The ram to set.
       * @return This builder for chaining.
       */
      public Builder setRam(int value) {
        bitField0_ |= 0x00000002;
        ram_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ram = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRam() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ram_ = 0;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>required int32 size = 3;</code>
       * @return Whether the size field is set.
       */
      @java.lang.Override
      public boolean hasSize() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 size = 3;</code>
       * @return The size.
       */
      @java.lang.Override
      public int getSize() {
        return size_;
      }
      /**
       * <code>required int32 size = 3;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(int value) {
        bitField0_ |= 0x00000004;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 size = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        size_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Hardware)
    }

    // @@protoc_insertion_point(class_scope:Hardware)
    private static final Mobile.Hardware DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Mobile.Hardware();
    }

    public static Mobile.Hardware getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Hardware>
        PARSER = new com.google.protobuf.AbstractParser<Hardware>() {
      @java.lang.Override
      public Hardware parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hardware(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hardware> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hardware> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Mobile.Hardware getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MobilePhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MobilePhone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string brand = 1;</code>
     * @return Whether the brand field is set.
     */
    boolean hasBrand();
    /**
     * <code>required string brand = 1;</code>
     * @return The brand.
     */
    java.lang.String getBrand();
    /**
     * <code>required string brand = 1;</code>
     * @return The bytes for brand.
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>required .Hardware hardware = 2;</code>
     * @return Whether the hardware field is set.
     */
    boolean hasHardware();
    /**
     * <code>required .Hardware hardware = 2;</code>
     * @return The hardware.
     */
    Mobile.Hardware getHardware();
    /**
     * <code>required .Hardware hardware = 2;</code>
     */
    Mobile.HardwareOrBuilder getHardwareOrBuilder();

    /**
     * <code>repeated string software = 3;</code>
     * @return A list containing the software.
     */
    java.util.List<java.lang.String>
        getSoftwareList();
    /**
     * <code>repeated string software = 3;</code>
     * @return The count of software.
     */
    int getSoftwareCount();
    /**
     * <code>repeated string software = 3;</code>
     * @param index The index of the element to return.
     * @return The software at the given index.
     */
    java.lang.String getSoftware(int index);
    /**
     * <code>repeated string software = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the software at the given index.
     */
    com.google.protobuf.ByteString
        getSoftwareBytes(int index);
  }
  /**
   * Protobuf type {@code MobilePhone}
   */
  public static final class MobilePhone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MobilePhone)
      MobilePhoneOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MobilePhone.newBuilder() to construct.
    private MobilePhone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MobilePhone() {
      brand_ = "";
      software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MobilePhone();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MobilePhone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              brand_ = bs;
              break;
            }
            case 18: {
              Mobile.Hardware.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = hardware_.toBuilder();
              }
              hardware_ = input.readMessage(Mobile.Hardware.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(hardware_);
                hardware_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                software_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              software_.add(bs);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          software_ = software_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Mobile.internal_static_MobilePhone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Mobile.internal_static_MobilePhone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Mobile.MobilePhone.class, Mobile.MobilePhone.Builder.class);
    }

    private int bitField0_;
    public static final int BRAND_FIELD_NUMBER = 1;
    private volatile java.lang.Object brand_;
    /**
     * <code>required string brand = 1;</code>
     * @return Whether the brand field is set.
     */
    @java.lang.Override
    public boolean hasBrand() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string brand = 1;</code>
     * @return The brand.
     */
    @java.lang.Override
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          brand_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string brand = 1;</code>
     * @return The bytes for brand.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HARDWARE_FIELD_NUMBER = 2;
    private Mobile.Hardware hardware_;
    /**
     * <code>required .Hardware hardware = 2;</code>
     * @return Whether the hardware field is set.
     */
    @java.lang.Override
    public boolean hasHardware() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .Hardware hardware = 2;</code>
     * @return The hardware.
     */
    @java.lang.Override
    public Mobile.Hardware getHardware() {
      return hardware_ == null ? Mobile.Hardware.getDefaultInstance() : hardware_;
    }
    /**
     * <code>required .Hardware hardware = 2;</code>
     */
    @java.lang.Override
    public Mobile.HardwareOrBuilder getHardwareOrBuilder() {
      return hardware_ == null ? Mobile.Hardware.getDefaultInstance() : hardware_;
    }

    public static final int SOFTWARE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList software_;
    /**
     * <code>repeated string software = 3;</code>
     * @return A list containing the software.
     */
    public com.google.protobuf.ProtocolStringList
        getSoftwareList() {
      return software_;
    }
    /**
     * <code>repeated string software = 3;</code>
     * @return The count of software.
     */
    public int getSoftwareCount() {
      return software_.size();
    }
    /**
     * <code>repeated string software = 3;</code>
     * @param index The index of the element to return.
     * @return The software at the given index.
     */
    public java.lang.String getSoftware(int index) {
      return software_.get(index);
    }
    /**
     * <code>repeated string software = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the software at the given index.
     */
    public com.google.protobuf.ByteString
        getSoftwareBytes(int index) {
      return software_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBrand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHardware()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHardware().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, brand_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getHardware());
      }
      for (int i = 0; i < software_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, software_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, brand_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getHardware());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < software_.size(); i++) {
          dataSize += computeStringSizeNoTag(software_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSoftwareList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Mobile.MobilePhone)) {
        return super.equals(obj);
      }
      Mobile.MobilePhone other = (Mobile.MobilePhone) obj;

      if (hasBrand() != other.hasBrand()) return false;
      if (hasBrand()) {
        if (!getBrand()
            .equals(other.getBrand())) return false;
      }
      if (hasHardware() != other.hasHardware()) return false;
      if (hasHardware()) {
        if (!getHardware()
            .equals(other.getHardware())) return false;
      }
      if (!getSoftwareList()
          .equals(other.getSoftwareList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBrand()) {
        hash = (37 * hash) + BRAND_FIELD_NUMBER;
        hash = (53 * hash) + getBrand().hashCode();
      }
      if (hasHardware()) {
        hash = (37 * hash) + HARDWARE_FIELD_NUMBER;
        hash = (53 * hash) + getHardware().hashCode();
      }
      if (getSoftwareCount() > 0) {
        hash = (37 * hash) + SOFTWARE_FIELD_NUMBER;
        hash = (53 * hash) + getSoftwareList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Mobile.MobilePhone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Mobile.MobilePhone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Mobile.MobilePhone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Mobile.MobilePhone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Mobile.MobilePhone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Mobile.MobilePhone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Mobile.MobilePhone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Mobile.MobilePhone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Mobile.MobilePhone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Mobile.MobilePhone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Mobile.MobilePhone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Mobile.MobilePhone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Mobile.MobilePhone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MobilePhone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MobilePhone)
        Mobile.MobilePhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Mobile.internal_static_MobilePhone_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Mobile.internal_static_MobilePhone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Mobile.MobilePhone.class, Mobile.MobilePhone.Builder.class);
      }

      // Construct using Mobile.MobilePhone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHardwareFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        brand_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (hardwareBuilder_ == null) {
          hardware_ = null;
        } else {
          hardwareBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Mobile.internal_static_MobilePhone_descriptor;
      }

      @java.lang.Override
      public Mobile.MobilePhone getDefaultInstanceForType() {
        return Mobile.MobilePhone.getDefaultInstance();
      }

      @java.lang.Override
      public Mobile.MobilePhone build() {
        Mobile.MobilePhone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Mobile.MobilePhone buildPartial() {
        Mobile.MobilePhone result = new Mobile.MobilePhone(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.brand_ = brand_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (hardwareBuilder_ == null) {
            result.hardware_ = hardware_;
          } else {
            result.hardware_ = hardwareBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          software_ = software_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.software_ = software_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Mobile.MobilePhone) {
          return mergeFrom((Mobile.MobilePhone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Mobile.MobilePhone other) {
        if (other == Mobile.MobilePhone.getDefaultInstance()) return this;
        if (other.hasBrand()) {
          bitField0_ |= 0x00000001;
          brand_ = other.brand_;
          onChanged();
        }
        if (other.hasHardware()) {
          mergeHardware(other.getHardware());
        }
        if (!other.software_.isEmpty()) {
          if (software_.isEmpty()) {
            software_ = other.software_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSoftwareIsMutable();
            software_.addAll(other.software_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasBrand()) {
          return false;
        }
        if (!hasHardware()) {
          return false;
        }
        if (!getHardware().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Mobile.MobilePhone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Mobile.MobilePhone) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object brand_ = "";
      /**
       * <code>required string brand = 1;</code>
       * @return Whether the brand field is set.
       */
      public boolean hasBrand() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string brand = 1;</code>
       * @return The brand.
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            brand_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string brand = 1;</code>
       * @return The bytes for brand.
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string brand = 1;</code>
       * @param value The brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string brand = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>required string brand = 1;</code>
       * @param value The bytes for brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        brand_ = value;
        onChanged();
        return this;
      }

      private Mobile.Hardware hardware_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Mobile.Hardware, Mobile.Hardware.Builder, Mobile.HardwareOrBuilder> hardwareBuilder_;
      /**
       * <code>required .Hardware hardware = 2;</code>
       * @return Whether the hardware field is set.
       */
      public boolean hasHardware() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required .Hardware hardware = 2;</code>
       * @return The hardware.
       */
      public Mobile.Hardware getHardware() {
        if (hardwareBuilder_ == null) {
          return hardware_ == null ? Mobile.Hardware.getDefaultInstance() : hardware_;
        } else {
          return hardwareBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Hardware hardware = 2;</code>
       */
      public Builder setHardware(Mobile.Hardware value) {
        if (hardwareBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hardware_ = value;
          onChanged();
        } else {
          hardwareBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Hardware hardware = 2;</code>
       */
      public Builder setHardware(
          Mobile.Hardware.Builder builderForValue) {
        if (hardwareBuilder_ == null) {
          hardware_ = builderForValue.build();
          onChanged();
        } else {
          hardwareBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Hardware hardware = 2;</code>
       */
      public Builder mergeHardware(Mobile.Hardware value) {
        if (hardwareBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              hardware_ != null &&
              hardware_ != Mobile.Hardware.getDefaultInstance()) {
            hardware_ =
              Mobile.Hardware.newBuilder(hardware_).mergeFrom(value).buildPartial();
          } else {
            hardware_ = value;
          }
          onChanged();
        } else {
          hardwareBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Hardware hardware = 2;</code>
       */
      public Builder clearHardware() {
        if (hardwareBuilder_ == null) {
          hardware_ = null;
          onChanged();
        } else {
          hardwareBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .Hardware hardware = 2;</code>
       */
      public Mobile.Hardware.Builder getHardwareBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHardwareFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Hardware hardware = 2;</code>
       */
      public Mobile.HardwareOrBuilder getHardwareOrBuilder() {
        if (hardwareBuilder_ != null) {
          return hardwareBuilder_.getMessageOrBuilder();
        } else {
          return hardware_ == null ?
              Mobile.Hardware.getDefaultInstance() : hardware_;
        }
      }
      /**
       * <code>required .Hardware hardware = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Mobile.Hardware, Mobile.Hardware.Builder, Mobile.HardwareOrBuilder> 
          getHardwareFieldBuilder() {
        if (hardwareBuilder_ == null) {
          hardwareBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Mobile.Hardware, Mobile.Hardware.Builder, Mobile.HardwareOrBuilder>(
                  getHardware(),
                  getParentForChildren(),
                  isClean());
          hardware_ = null;
        }
        return hardwareBuilder_;
      }

      private com.google.protobuf.LazyStringList software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSoftwareIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          software_ = new com.google.protobuf.LazyStringArrayList(software_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string software = 3;</code>
       * @return A list containing the software.
       */
      public com.google.protobuf.ProtocolStringList
          getSoftwareList() {
        return software_.getUnmodifiableView();
      }
      /**
       * <code>repeated string software = 3;</code>
       * @return The count of software.
       */
      public int getSoftwareCount() {
        return software_.size();
      }
      /**
       * <code>repeated string software = 3;</code>
       * @param index The index of the element to return.
       * @return The software at the given index.
       */
      public java.lang.String getSoftware(int index) {
        return software_.get(index);
      }
      /**
       * <code>repeated string software = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the software at the given index.
       */
      public com.google.protobuf.ByteString
          getSoftwareBytes(int index) {
        return software_.getByteString(index);
      }
      /**
       * <code>repeated string software = 3;</code>
       * @param index The index to set the value at.
       * @param value The software to set.
       * @return This builder for chaining.
       */
      public Builder setSoftware(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       * @param value The software to add.
       * @return This builder for chaining.
       */
      public Builder addSoftware(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       * @param values The software to add.
       * @return This builder for chaining.
       */
      public Builder addAllSoftware(
          java.lang.Iterable<java.lang.String> values) {
        ensureSoftwareIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, software_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSoftware() {
        software_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string software = 3;</code>
       * @param value The bytes of the software to add.
       * @return This builder for chaining.
       */
      public Builder addSoftwareBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSoftwareIsMutable();
        software_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MobilePhone)
    }

    // @@protoc_insertion_point(class_scope:MobilePhone)
    private static final Mobile.MobilePhone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Mobile.MobilePhone();
    }

    public static Mobile.MobilePhone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MobilePhone>
        PARSER = new com.google.protobuf.AbstractParser<MobilePhone>() {
      @java.lang.Override
      public MobilePhone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MobilePhone(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MobilePhone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MobilePhone> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Mobile.MobilePhone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Hardware_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Hardware_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MobilePhone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MobilePhone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mobile.proto\"2\n\010Hardware\022\013\n\003rom\030\001 \002(\005\022" +
      "\013\n\003ram\030\002 \002(\005\022\014\n\004size\030\003 \002(\005\"K\n\013MobilePhon" +
      "e\022\r\n\005brand\030\001 \002(\t\022\033\n\010hardware\030\002 \002(\0132\t.Har" +
      "dware\022\020\n\010software\030\003 \003(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Hardware_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Hardware_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Hardware_descriptor,
        new java.lang.String[] { "Rom", "Ram", "Size", });
    internal_static_MobilePhone_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MobilePhone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MobilePhone_descriptor,
        new java.lang.String[] { "Brand", "Hardware", "Software", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
